### ISSUE TITLE
I can't get automatic Japanese labeling in v030

### ISSUE THREAD

**Issue by rokujyushi** [spicytigermeat/LabelMakr#4]
![image](https://github.com/spicytigermeat/LabelMakr/assets/93469977/068166bd-3868-4cb5-8f46-dd652d20bb7f)
I immediately installed the tool and tried to use it, but it fails here.
Will a future update allow me to use it in the same way as the previous version?

**Comment by spicytigermeat** [comment]
Hi rokujyushi!!

Thanks for pointing this out to me, I've reuploaded the release of v030, titled v030_fix [here](https://github.com/spicytigermeat/LabelMakr/releases/tag/v030).

You can download that version, and move the `g2p-jp` folder from the new release to the current version, I forgot to include it in the latest release.

Pls let me know if that fixes this issue!

**Comment by spicytigermeat** [comment]
Closing issue due to the inability to recreate the issue after the update, and inactivity.
